### ISSUE TITLE
Add option to disable first party detection

### ISSUE THREAD

**Issue by amyreese** [amyreese/ruff-api#53]
### Description

Equivalent of:

```toml
[tool.ruff.lint.isort]
detect-same-package = false
```
